### ISSUE TITLE
What Opencart versions does this module support?

### ISSUE THREAD

**Issue by xguntis** [ecomcharge/opencart-bepaid-payment-module#1]

**Comment by ecomcharge** [comment]
hello,

the module was developed and tested with the 1.5.6 version

**Comment by xguntis** [comment]
thanks, is there version for 2.0.x coming? when?

**Comment by ecomcharge** [comment]
let me test the module against 2.0.x version. briefly look showed that nothing changed in payment modules code. I faced with the issue when I can't install extension via installer. opencart wants to have open FTP for it.

**Comment by avsh** [comment]
the version for OpenCart 2.0.x is released
